services:
  - type: web
    name: surya-store
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/products
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8080
